name: 500Map
version: '${version}'
main: me.j0keer.fhmap.Main
api-version: 1.19
depend:
  - PlaceholderAPI
  - FastAsyncWorldEdit

description: Plugin for all relationated to 500 dollars map to SpreenDMC

libraries:
  - org.projectlombok:lombok:1.18.28
  - com.github.cryptomorin:XSeries:9.3.1
